version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: inventario_user
      POSTGRES_PASSWORD: inventario_password
      POSTGRES_DB: inventario_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
